package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// Progress: what has actually been finished, and when.
//
// The plan already knows what is done RIGHT NOW -- Assess() recomputes it from
// the world on every run. What it cannot know is what was done SINCE LAST TIME,
// and that is the only part worth interrupting someone for. Finishing something
// is the one event in this whole system that deserves a message of its own.
//
// So a small file remembers the date each step first read as done. Two things
// fall out of it: an achievement can be detected exactly once, and the roadmap
// gains real dates rather than a list of ticks with no history.

type Progress struct {
	// Done maps a step id to the date it was FIRST seen finished. First, not
	// last: a step that flickers -- itch.io unreachable for an hour, say --
	// must not re-announce itself when it comes back.
	Done map[string]string `json:"done"`
}

func LoadProgress(path string) Progress {
	p := Progress{Done: map[string]string{}}
	b, err := os.ReadFile(path)
	if err != nil {
		return p // no file yet is not an error; it is the first run
	}
	if json.Unmarshal(b, &p) != nil || p.Done == nil {
		p.Done = map[string]string{}
	}
	return p
}

func SaveProgress(path string, p Progress) error {
	b, err := json.MarshalIndent(p, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

// Achievements are steps finished since the last run.
//
// A CONFLICT never counts. A step someone marked done that the world disagrees
// with is the opposite of an achievement, and celebrating it would be the
// cheerful version of the bug this project keeps finding: reporting success for
// work that did not happen.
func Achievements(prev Progress, as []Assessment) []Assessment {
	var out []Assessment
	for _, a := range as {
		if a.Status == StatusDone && prev.Done[a.Step.ID] == "" {
			out = append(out, a)
		}
	}
	return out
}

// Record folds today's assessment into the progress file. Steps already
// recorded keep their original date.
func Record(p Progress, as []Assessment, today string) Progress {
	if p.Done == nil {
		p.Done = map[string]string{}
	}
	for _, a := range as {
		if a.Status == StatusDone && p.Done[a.Step.ID] == "" {
			p.Done[a.Step.ID] = today
		}
	}
	return p
}

// --- the roadmap ------------------------------------------------------------

// RenderRoadmap writes the part of the roadmap that MOVES: the live plan, its
// real dates, and what is blocking the rest.
//
// It deliberately does not restate the three tracks. Those change a few times a
// year and belong in prose a human writes; this changes weekly and should never
// be maintained by hand, because a hand-maintained progress table is a stale
// progress table.
func RenderRoadmap(as []Assessment, p Progress, w World) string {
	var b strings.Builder

	done, total := 0, 0
	for _, a := range as {
		total++
		if a.Status == StatusDone {
			done++
		}
	}

	fmt.Fprintf(&b, "# Roadmap — where the plan actually is\n\n")
	fmt.Fprintf(&b, "Generated by the Orchestrator on %s. Do not edit by hand: it is\n",
		w.Now.Format("2006-01-02"))
	fmt.Fprintf(&b, "rewritten on every run, and a hand-maintained progress table is a stale one.\n\n")

	// A bar, because a fraction is read and a bar is seen.
	filled := 0
	if total > 0 {
		filled = done * 24 / total
	}
	fmt.Fprintf(&b, "```\n%s%s  %d of %d steps\n```\n\n",
		strings.Repeat("█", filled), strings.Repeat("·", 24-filled), done, total)

	fmt.Fprintf(&b, "## The live plan\n\n")
	fmt.Fprintf(&b, "| | Step | Phase | Status |\n|---|---|---|---|\n")
	for _, a := range as {
		mark, status := "☐", string(a.Status)
		switch a.Status {
		case StatusDone:
			mark = "☑"
			if d := p.Done[a.Step.ID]; d != "" {
				status = "done " + d
			}
		case StatusReady:
			mark = "▶"
			status = fmt.Sprintf("**ready — %d min**", a.Step.Minutes)
		case StatusConflict:
			mark = "⚠"
			status = "**check** — " + a.Note
		case StatusBlocked:
			status = a.Note
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", mark, a.Step.Title, a.Step.Phase, status)
	}

	if n, ok := Next(as); ok {
		fmt.Fprintf(&b, "\n## Next\n\n**%s** — %d minutes.\n\nOpen `%s`.\n",
			n.Step.Title, n.Step.Minutes, n.Step.Doc)
		if n.Step.Why != "" {
			fmt.Fprintf(&b, "\n%s.\n", strings.ToUpper(n.Step.Why[:1])+n.Step.Why[1:])
		}
	} else {
		fmt.Fprintf(&b, "\n## Next\n\nNothing is available. Everything is either finished or waiting.\n")
	}

	// Only the gates that are genuinely holding something up, with the date
	// where a date exists. A list of every possible blocker is a wall.
	var waiting []string
	for _, a := range as {
		if a.Status == StatusBlocked {
			waiting = append(waiting, fmt.Sprintf("- **%s** — %s", a.Step.Title, a.Note))
		}
	}
	if len(waiting) > 0 {
		sort.Strings(waiting)
		fmt.Fprintf(&b, "\n## Waiting on something\n\n%s\n", strings.Join(waiting, "\n"))
	}

	_, verdict, action := Diagnose(w)
	fmt.Fprintf(&b, "\n## The funnel\n\n%s\n\n%s.\n", verdict,
		strings.ToUpper(action[:1])+action[1:])

	fmt.Fprintf(&b, "\n---\n\nThe wider picture — the three tracks, the estimates, and the gate on each\n")
	fmt.Fprintf(&b, "remaining phase — is in [docs/timeline.md](docs/timeline.md) and the\n")
	fmt.Fprintf(&b, "published roadmap. Those move a few times a year; this moves weekly.\n")
	return b.String()
}

// CelebrationText is its own message, sent before the digest.
//
// Restraint on purpose. Finishing a step is worth a line and a number, not
// confetti -- an agent that congratulates you for everything is one you learn
// to ignore, and then it cannot tell you the thing that mattered.
func CelebrationText(done []Assessment, as []Assessment, p Progress) string {
	total, finished := len(as), 0
	for _, a := range as {
		if a.Status == StatusDone {
			finished++
		}
	}

	var b strings.Builder
	if len(done) == 1 {
		fmt.Fprintf(&b, "Done: %s\n", done[0].Step.Title)
	} else {
		fmt.Fprintf(&b, "Done:\n")
		for _, a := range done {
			fmt.Fprintf(&b, "  • %s\n", a.Step.Title)
		}
	}
	fmt.Fprintf(&b, "\n%d of %d steps complete.\n", finished, total)

	if n, ok := Next(as); ok {
		fmt.Fprintf(&b, "\nNext: %s (%d min)\n%s\n", n.Step.Title, n.Step.Minutes, n.Step.Doc)
	}
	return b.String()
}

func today(t time.Time) string { return t.UTC().Format("2006-01-02") }
